### GET example.com
GET http://www.example.com/

### GET JSON placeholder
GET https://jsonplaceholder.typicode.com/posts

### GET JSON placeholder post 1
GET https://jsonplaceholder.typicode.com/posts/1

### PUT if exists: update/ else: create
PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
    "userId": 1,
    "id": 1,
    "title": "new title",
    "body": "new body text"
}

### DELETE post 1
DELETE https://jsonplaceholder.typicode.com/posts/1

### POST create one post
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "New post!",
    "body": "This is my post!"
}

### GET Mozilla developer example
GET / HTTP/1.1
Host: developer.mozilla.org
Accept-language: en

