### GET example for own server
GET http://localhost:3000/

### POST
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "text": "This is a POST request"
}

### PUT
PUT http://localhost:3000/api/cards

Content-Type: application/json

{
    "text": "This is a PUT request"
}

### PATCH 
PATCH http://localhost:3000/api/cards

Content-Type: application/json

{
    "text": "This is a PATCH request"
}

### DELETE
DELETE http://localhost:3000/api/cards

Content-Type: application/json

{
    "text": "This is a DELETE request"
}