### GET example for own server
GET http://localhost:3000/api/cards

### GET one card from array
GET http://localhost:3000/api/cards/61543c7a6e01dc73254bb6c3

### GET try to get one card with id that does not exist from array
GET http://localhost:3000/api/cards/61543c7a6e01dc73254bb6c4

### POST
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "text": "The new Card.",
    "author": "Peter Petersen"
}

### PUT
PUT http://localhost:3000/api/cards/1234
Content-Type: application/json

{
    "text": "Hi, my name is Bernardo.",
    "author": "Bernardo"
}

### PUT update existing entry
PUT http://localhost:3000/api/cards/12345abc
Content-Type: application/json

{
    "author": "Erling",
    "text": "Hi, my name is Erling."
}

### PATCH 
PATCH http://localhost:3000/api/cards/61545bf26e01dc73254bb6c4
Content-Type: application/json

{
    "text": "Cool new text!"
}

### DELETE
DELETE http://localhost:3000/api/cards/61546bd7ff60fe3ae9f7f277