### GET example for own server
GET http://localhost:3000/api/cards

### GET one card from array
GET http://localhost:3000/api/cards/12345abc

### GET try to get one card with id that does not exist from array
GET http://localhost:3000/api/cards/54321abc

### POST
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "text": "This is a POST request",
    "author": "Peter Petersen"
}

### PUT
PUT http://localhost:3000/api/cards/1234

Content-Type: application/json

{
    "text": "This is a PUT request"
}

### PATCH 
PATCH http://localhost:3000/api/cards/12345abc
Content-Type: application/json

{
    "text": "This is the updated text"
}

### DELETE
DELETE http://localhost:3000/api/cards/1234abcd